---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: face.faces.svc.cluster.local
  namespace: faces
spec:
  routes:
  - condition:
      method: GET
    name: GET /
    isRetryable: true
    timeout: 250ms
